<?php
return [
    /*
    |--------------------------------------------------------------------------
    | DROPDOWN FOR TYPES FIELDS
    |--------------------------------------------------------------------------
    |
    */
    'default_state' => ['open' => 'open','closed' => 'closed'],
    'sections' => ['BOT_PROPERTY' => 'Bot Properties','CATEGORY_GROUP' => 'Category Groups'],
    'item_status' => ['A' => 'Active','H' => 'Hidden', 'T' => 'Test'],
    'turn_status' => ['O' => 'Open', 'C' => 'Closed', 'F' => 'Failed', 'E' => 'Error', 'I' => 'In Progress'],
    'turn_source' => ['human' => 'Human', 'multiple' => 'Multiple', 'tag' => 'Tag', 'srai' => 'SRAI'],


    'avatar_top_type' => [
        'NoHair' => 'NoHair',
        'Eyepatch' => 'Eyepatch',
        'Hat' => 'Hat',
        'Hijab' => 'Hijab',
        'Turban' => 'Turban',
        'WinterHat1' => 'WinterHat1',
        'WinterHat2' => 'WinterHat2',
        'WinterHat3' => 'WinterHat3',
        'WinterHat4' => 'WinterHat4',
        'LongHairBigHair' => 'LongHairBigHair',
        'LongHairBob' => 'LongHairBob',
        'LongHairBun' => 'LongHairBun',
        'LongHairCurly' => 'LongHairCurly',
        'LongHairCurvy' => 'LongHairCurvy',
        'LongHairDreads' => 'LongHairDreads',
        'LongHairFrida' => 'LongHairFrida',
        'LongHairFro' => 'LongHairFro',
        'LongHairFroBand' => 'LongHairFroBand',
        'LongHairNotTooLong' => 'LongHairNotTooLong',
        'LongHairShavedSides' => 'LongHairShavedSides',
        'LongHairMiaWallace' => 'LongHairMiaWallace',
        'LongHairStraight' => 'LongHairStraight',
        'LongHairStraight2' => 'LongHairStraight2',
        'LongHairStraightStrand' => 'LongHairStraightStrand',
        'ShortHairDreads01' => 'ShortHairDreads01',
        'ShortHairDreads02' => 'ShortHairDreads02',
        'ShortHairFrizzle' => 'ShortHairFrizzle',
        'ShortHairShaggyMullet' => 'ShortHairShaggyMullet',
        'ShortHairShortCurly' => 'ShortHairShortCurly',
        'ShortHairShortFlat' => 'ShortHairShortFlat',
        'ShortHairShortRound' => 'ShortHairShortRound',
        'ShortHairShortWaved' => 'ShortHairShortWaved',
        'ShortHairSides' => 'ShortHairSides',
        'ShortHairTheCaesar' => 'ShortHairTheCaesar',
        'ShortHairTheCaesarSidePart' => 'ShortHairTheCaesarSidePart'
    ],

    'avatar_accessories_type' => [
        'Blank' => 'Blank',
        'Kurt' => 'Kurt',
        'Prescription01' => 'Prescription01',
        'Prescription02' => 'Prescription02',
        'Round' => 'Round',
        'Sunglasses' => 'Sunglasses',
        'Wayfarers' => 'Wayfarers'
    ],

    'avatar_hair_color' => [
        'Auburn' => 'Auburn',
        'Black' => 'Black',
        'Blonde' => 'Blonde',
        'BlondeGolden' => 'BlondeGolden',
        'Brown' => 'Brown',
        'BrownDark' => 'BrownDark',
        'PastelPink' => 'PastelPink',
        'Red' => 'Red',
        'SilverGray' => 'SilverGray'
    ],

    'avatar_facial_hair_type' => [
        'Blank' => 'Blank',
        'Black' => 'Black',
        'BeardMedium' => 'BeardMedium',
        'BeardLight' => 'BeardLight',
        'BeardMajestic' => 'BeardMajestic',
        'MoustacheFancy' => 'MoustacheFancy',
        'MoustacheMagnum' => 'MoustacheMagnum',
    ],

    'avatar_facial_hair_color' => [
        'Auburn' => 'Auburn',
        'Black' => 'Black',
        'Blonde' => 'Blonde',
        'BlondeGolden' => 'BlondeGolden',
        'Brown' => 'Brown',
        'BrownDark' => 'BrownDark',
        'Platinum' => 'Platinum',
        'Red' => 'Red',
    ],



    'avatar_hat_color' => [
        'Black' => 'Black',
        'Blue01' => 'Blue01',
        'Blue02' => 'Blue02',
        'Blue03' => 'Blue03',
        'Gray01' => 'Gray01',
        'Gray02' => 'Gray02',
        'Heather' => 'Heather',
        'PastelBlue' => 'PastelBlue',
        'PastelGreen' => 'PastelGreen',
        'PastelOrange' => 'PastelOrange',
        'PastelRed' => 'PastelRed',
        'PastelYellow' => 'PastelYellow',
        'Pink' => 'Pink',
        'Red' => 'Red',
        'White' => 'White',
    ],


    'avatar_clothe_type' => [
        'BlazerShirt' => 'BlazerShirt',
        'BlazerSweater' => 'BlazerSweater',
        'CollarSweater' => 'CollarSweater',
        'GraphicShirt' => 'GraphicShirt',
        'Hoodie' => 'Hoodie',
        'Overall' => 'Overall',
        'ShirtCrewNeck' => 'ShirtCrewNeck',
        'ShirtScoopNeck' => 'ShirtScoopNeck',
        'ShirtVNeck' => 'ShirtVNeck'
    ],
    'avatar_clothe_color' => [
        'Black' => 'Black',
        'Blue01' => 'Blue01',
        'Blue02' => 'Blue02',
        'Blue03' => 'Blue03',
        'Gray01' => 'Gray01',
        'Gray02' => 'Gray02',
        'Heather' => 'Heather',
        'PastelBlue' => 'PastelBlue',
        'PastelGreen' => 'PastelGreen',
        'PastelOrange' => 'PastelOrange',
        'PastelRed' => 'PastelRed',
        'PastelYellow' => 'PastelYellow',
        'Pink' => 'Pink',
        'Red' => 'Red',
        'White' => 'White',
    ],
    'avatar_graphic_type' => [
        'Bat' => 'Bat',
        'Cumbia' => 'Cumbia',
        'Deer' => 'Deer',
        'Diamond' => 'Diamond',
        'Hola' => 'Hola',
        'Pizza' => 'Pizza',
        'Resist' => 'Resist',
        'Selena' => 'Selena',
        'Bear' => 'Bear',
        'SkullOutline' => 'SkullOutline',
        'Skull' => 'Skull',
    ],
    'avatar_eye_type' => [

        'Close' => 'Close',
        'Cry' => 'Cry',
        'Default' => 'Default',
        'Dizzy' => 'Dizzy',
        'EyeRoll' => 'EyeRoll',
        'Happy' => 'Happy',
        'Hearts' => 'Hearts',
        'Side' => 'Side',
        'Squint' => 'Squint',
        'Surprised' => 'Surprised',
        'Wink' => 'Wink',
        'WinkWacky' => 'WinkWacky',
    ],
    'avatar_eye_brow_type' => [
        'Angry' => 'Angry',
        'AngryNatural' => 'AngryNatural',
        'Default' => 'Default',
        'DefaultNatural' => 'DefaultNatural',
        'FlatNatural' => 'FlatNatural',
        'RaisedExcited' => 'RaisedExcited',
        'RaisedExcitedNatural' => 'RaisedExcitedNatural',
        'SadConcerned' => 'SadConcerned',
        'SadConcernedNatural' => 'SadConcernedNatural',
        'UnibrowNatural' => 'UnibrowNatural',
        'UpDown' => 'UpDown',
        'UpDownNatural' => 'UpDownNatural',
    ],
    'avatar_mouth_type' => [
        'Concerned' => 'Concerned',
        'Default' => 'Default',
        'Disbelief' => 'Disbelief',
        'Eating' => 'Eating',
        'Grimace' => 'Grimace',
        'Sad' => 'Sad',
        'ScreamOpen' => 'ScreamOpen',
        'Serious' => 'Serious',
        'Smile' => 'Smile',
        'Tongue' => 'Tongue',
        'Twinkle' => 'Twinkle',
        'Vomit' => 'Vomit',
    ],
    'avatar_skin_color' => [
        'Tanned' => 'Tanned',
        'Yellow' => 'Yellow',
        'Pale' => 'Pale',
        'Light' => 'Light',
        'Brown' => 'Brown',
        'DarkBrown' => 'DarkBrown',
        'Black' => 'Black',
    ],
    'suggested_category_groups' => [
        'std-65percent',
        'std-atomic',
        'std-botmaster',
        'std-brain',
        'std-critical',
        'std-dictionary',
        'std-gender',
        'std-geography',
        'std-gossip',
        'std-hello',
        'std-howmany',
        'std-knowledge',
        'std-learn',
        'std-numbers',
        'std-personality',
        'std-pickup',
        'std-profile',
        'std-rating',
        'std-sextalk',
        'std-shutup',
        'std-srai',
        'std-suffixes',
        'std-that',
        'std-yesno',
    ]
];
