<?php

return [
    /*
    |--------------------------------------------------------------------------
    | THE DEFAULT SECTIONS (only used if not set manually)
    | These are also the recommend properties
    |--------------------------------------------------------------------------
    |
    */
    'bot_properties' => [
        'sections' => [
            'bot-personality' => [
                'name'=>'Bot Personality',
                'default_state'=>'open',
                'order' => 1,
            ],
            'social-media' => [
                'name'=>'Social Media',
                'default_state'=>'open',
                'order' => 2,
            ]
        ],
        'fields' => [
            'age'=> 'bot-personality',
            'baseballteam'=> 'bot-personality',
            'birthday'=> 'bot-personality',
            'birthplace'=> 'bot-personality',
            'botmaster'=> 'bot-personality',
            'boyfriend'=> 'bot-personality',
            'build'=> 'bot-personality',
            'celebrities'=> 'bot-personality',
            'celebrity'=> 'bot-personality',
            'class'=> 'bot-personality',
            'emotions'=> 'bot-personality',
            'ethics'=> 'bot-personality',
            'etype'=> 'bot-personality',
            'family'=> 'bot-personality',
            'favoriteactor'=> 'bot-personality',
            'favoriteactress'=> 'bot-personality',
            'favoriteartist'=> 'bot-personality',
            'favoriteauthor'=> 'bot-personality',
            'favoriteband'=> 'bot-personality',
            'favoritebook'=> 'bot-personality',
            'favoritecolor'=> 'bot-personality',
            'favoritefood'=> 'bot-personality',
            'favoritemovie'=> 'bot-personality',
            'favoritesong'=> 'bot-personality',
            'favoritesport'=> 'bot-personality',
            'feelings'=> 'bot-personality',
            'footballteam'=> 'bot-personality',
            'forfun'=> 'bot-personality',
            'friend'=> 'bot-personality',
            'friends'=> 'bot-personality',
            'gender'=> 'bot-personality',
            'genus'=> 'bot-personality',
            'girlfriend'=> 'bot-personality',
            'hockeyteam'=> 'bot-personality',
            'kindmusic'=> 'bot-personality',
            'kingdom'=> 'bot-personality',
            'language'=> 'bot-personality',
            'location'=> 'bot-personality',
            'looklike'=> 'bot-personality',
            'master'=> 'bot-personality',
            'msagent'=> 'bot-personality',
            'name'=> 'bot-personality',
            'nationality'=> 'bot-personality',
            'order'=> 'bot-personality',
            'orientation'=> 'bot-personality',
            'party'=> 'bot-personality',
            'phylum'=> 'bot-personality',
            'president'=> 'bot-personality',
            'question'=> 'bot-personality',
            'religion'=> 'bot-personality',
            'sign'=> 'bot-personality',
            'size'=> 'bot-personality',
            'species'=> 'bot-personality',
            'talkabout'=> 'bot-personality',
            'version'=> 'bot-personality',
            'vocabulary'=> 'bot-personality',
            'wear'=> 'bot-personality',
            'website'=> 'social-media',
            'facebook'=> 'social-media',
            'twitter'=> 'social-media',
            'linkedin'=> 'social-media',
            'tiktok'=> 'social-media',
            'instagram'=> 'social-media',
            'email'=> 'social-media',
        ],
    ],
    'category_groups' => [
        'sections' => [
            'test-categories' => [
                'name'=>'Test Categories',
                'default_state'=>'closed',
                'order' => 1000,
            ],
            'conversation-flow' => [
                'name'=>'Conversation Flow',
                'default_state'=>'open',
                'order' => 1,
            ],
            'personality' => [
                'name'=>'Personality',
                'default_state'=>'open',
                'order' => 2,
            ],
            'general-knowledge' => [
                'name'=>'General Knowledge',
                'default_state'=>'open',
                'order' => 3,
            ],
            'special-routines' => [
                'name'=>'Special Routines',
                'default_state'=>'open',
                'order' => 4,
            ],
            'critical-flow' => [
                'name'=>'Critical Flow',
                'default_state'=>'open',
                'order' => 5,
            ],
            'fun-talk' => [
                'name'=>'Fun Talk (jokes)',
                'default_state'=>'open',
                'order' => 6,
            ]
        ],
        'fields' => [
            'dev-testcases' => 'test-categories',
            'std-critical' => 'critical-flow',
            'std-rating' => 'special-routines',
            'std-hello' => 'conversation-flow',
            'std-65percent' => 'conversation-flow',
            'std-atomic' => 'conversation-flow',
            'std-botmaster' => 'personality',
            'std-brain' => 'conversation-flow',
            'std-dictionary' => 'general-knowledge',
            'std-howto' => 'general-knowledge',
            'std-inventions' => 'general-knowledge',
            'std-gender' => 'conversation-flow',
            'std-geography' => 'general-knowledge',
            'std-german' => 'general-knowledge',
            'std-gossip' => 'special-routines',
            'std-knowledge' => 'general-knowledge',
            'std-lizards' => 'general-knowledge',
            'std-numbers' => 'general-knowledge',
            'std-personality' => 'personality',
            'std-pickup' => 'conversation-flow',
            'std-politics' => 'general-knowledge',
            'std-profile' => 'personality',
            'std-religion' => 'general-knowledge',
            'std-robot' => 'general-knowledge',
            'std-sports' => 'general-knowledge',
            'std-sales' => 'conversation-flow',
            'std-sextalk' => 'conversation-flow',
            'std-srai' => 'conversation-flow',
            'std-that' => 'conversation-flow',
            'std-suffixes' => 'conversation-flow',
            'std-turing' => 'general-knowledge',
            'std-yesno' => 'conversation-flow',
            'std-learn' => 'special-routines',
            'std-happybirthday' => 'general-knowledge',
            'std-horoscope' => 'general-knowledge',
            'std-howmany' => 'conversation-flow',
            'std-jokes' => 'fun-talk',
            'std-knockknock' => 'fun-talk',
            'std-yomama' => 'fun-talk',
            'std-shutup' => 'conversation-flow',
            ]
        ]

];
